In [2]:
import torch
import torch.nn as nn

In [3]:
x = torch.randn(10,5)  # input tensor
w = torch.randn(5, 3, requires_grad=True)

print(x.shape, w.shape)
print(x,w)

torch.Size([10, 5]) torch.Size([5, 3])
tensor([[ 0.0341,  2.3685,  0.2052, -0.8588,  1.4128],
        [-0.8003,  1.6307, -0.6141,  1.1474,  1.8649],
        [ 1.2807, -0.6298,  0.7531,  0.0960,  0.1711],
        [-0.9039, -0.1403, -2.0878, -0.1966, -2.1573],
        [-1.2338,  0.3702, -0.6107,  0.1061, -0.3320],
        [-0.5954, -0.7624, -0.6006,  0.1615,  0.2094],
        [-1.4292,  0.2433,  1.1357, -0.5114,  0.7560],
        [-0.4434, -0.1687,  0.7302, -1.6523,  0.1455],
        [ 0.9393,  0.2076,  0.1075,  2.0984,  1.2508],
        [-0.2124, -1.2491, -0.3026, -0.7668, -0.9790]]) tensor([[-0.7436, -0.6397,  1.8075],
        [ 0.8778,  0.1621, -1.7515],
        [ 0.3638,  2.2540, -0.4775],
        [ 0.7711, -0.9065, -1.5571],
        [-0.8579,  0.5668,  0.2420]], requires_grad=True)


In [4]:
#matrix multiplication
y1 = x@w
print(y1.shape)
print(y1)
y2 = x.matmul(w)
print(y2)
y3 = torch.matmul(x, w)
print(y3)

torch.Size([10, 3])
tensor([[ 0.2541,  2.4038, -2.5056],
        [ 1.0880, -0.5910, -5.3448],
        [-1.3039,  0.7862,  2.9503],
        [ 1.4886, -5.1947, -0.6070],
        [ 1.3869, -0.8115, -2.8325],
        [-0.5001, -1.1242,  0.3451],
        [ 0.6466,  4.4056, -2.5725],
        [-0.9516,  3.4825,  1.7534],
        [ 0.0678, -1.5182, -1.6819],
        [-0.7999, -0.6083,  2.9054]], grad_fn=<MmBackward0>)
tensor([[ 0.2541,  2.4038, -2.5056],
        [ 1.0880, -0.5910, -5.3448],
        [-1.3039,  0.7862,  2.9503],
        [ 1.4886, -5.1947, -0.6070],
        [ 1.3869, -0.8115, -2.8325],
        [-0.5001, -1.1242,  0.3451],
        [ 0.6466,  4.4056, -2.5725],
        [-0.9516,  3.4825,  1.7534],
        [ 0.0678, -1.5182, -1.6819],
        [-0.7999, -0.6083,  2.9054]], grad_fn=<MmBackward0>)
tensor([[ 0.2541,  2.4038, -2.5056],
        [ 1.0880, -0.5910, -5.3448],
        [-1.3039,  0.7862,  2.9503],
        [ 1.4886, -5.1947, -0.6070],
        [ 1.3869, -0.8115, -2.8325],
       

In [5]:
# matrix multiplication
linear = torch.nn.Linear(5, 3, bias=False)
print(linear.weight)
print(linear.bias)
linear.weight.data = w.T
print(w)
print(linear.weight)
y = linear(x)
print(y)
print(y3)

Parameter containing:
tensor([[ 0.2778,  0.3316, -0.4287,  0.2218, -0.2935],
        [ 0.2479,  0.2488,  0.2680,  0.3405,  0.1923],
        [ 0.1803,  0.1802, -0.0460,  0.0319, -0.0522]], requires_grad=True)
None
tensor([[-0.7436, -0.6397,  1.8075],
        [ 0.8778,  0.1621, -1.7515],
        [ 0.3638,  2.2540, -0.4775],
        [ 0.7711, -0.9065, -1.5571],
        [-0.8579,  0.5668,  0.2420]], requires_grad=True)
Parameter containing:
tensor([[-0.7436,  0.8778,  0.3638,  0.7711, -0.8579],
        [-0.6397,  0.1621,  2.2540, -0.9065,  0.5668],
        [ 1.8075, -1.7515, -0.4775, -1.5571,  0.2420]], requires_grad=True)
tensor([[ 0.2541,  2.4038, -2.5056],
        [ 1.0880, -0.5910, -5.3448],
        [-1.3039,  0.7862,  2.9503],
        [ 1.4886, -5.1947, -0.6070],
        [ 1.3869, -0.8115, -2.8325],
        [-0.5001, -1.1242,  0.3451],
        [ 0.6466,  4.4056, -2.5725],
        [-0.9516,  3.4825,  1.7534],
        [ 0.0678, -1.5182, -1.6819],
        [-0.7999, -0.6083,  2.9054]], gr

In [6]:
# element wise multiplcation

print(w)

z = w * w

print(z)

i = 3
j = 2
print(w[i][j]**2)

tensor([[-0.7436, -0.6397,  1.8075],
        [ 0.8778,  0.1621, -1.7515],
        [ 0.3638,  2.2540, -0.4775],
        [ 0.7711, -0.9065, -1.5571],
        [-0.8579,  0.5668,  0.2420]], requires_grad=True)
tensor([[0.5529, 0.4092, 3.2671],
        [0.7705, 0.0263, 3.0676],
        [0.1323, 5.0803, 0.2280],
        [0.5946, 0.8218, 2.4247],
        [0.7360, 0.3212, 0.0586]], grad_fn=<MulBackward0>)
tensor(2.4247, grad_fn=<PowBackward0>)


In [7]:
print(w, w.dtype, w.device)
w1 = w.bfloat16()
print(w1.dtype)

tensor([[-0.7436, -0.6397,  1.8075],
        [ 0.8778,  0.1621, -1.7515],
        [ 0.3638,  2.2540, -0.4775],
        [ 0.7711, -0.9065, -1.5571],
        [-0.8579,  0.5668,  0.2420]], requires_grad=True) torch.float32 cpu
torch.bfloat16


In [8]:
m1 = nn.Linear(20, 30)
m2 = nn.Linear(30, 40)
x = torch.randn(128, 20)
y1 = m1(x)
y2 = m2(y1)
print(y2.shape)

torch.Size([128, 40])


In [9]:
x_large = torch.randn(128, 4096,30, 20)
y1_large = m1(x_large)
y2_large = m2(y1_large)
print(y2.shape)

torch.Size([128, 40])


In [10]:
x_large = torch.randn(128, 4096,30, 20)
b, s, h, w = x_large.shape
print(b, s, h, w)
x_large = x_large.view(b * s * h, w)
print(x_large.shape)

y1 = m1(x_large)
y2 = m2(y1)
print(y2.shape)
y2 = y2.view(b, s, h, 40)
print(y2.shape)


128 4096 30 20
torch.Size([15728640, 20])
torch.Size([15728640, 40])
torch.Size([128, 4096, 30, 40])


In [11]:
x = torch.ones((1,1,5,5))
print(x)
x[:,:,:,0]=0
x[:,:,:,1]=0
x[:,:,0,:]=0
x[:,:,1,:]=0
print(x)
conv_w = torch.ones((1,1,3,3))

y = nn.functional.conv2d(x, conv_w)
print(y)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 1., 1., 1.],
          [0., 0., 1., 1., 1.],
          [0., 0., 1., 1., 1.]]]])
tensor([[[[1., 2., 3.],
          [2., 4., 6.],
          [3., 6., 9.]]]])


In [12]:
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

train_dataloader = DataLoader(training_data, batch_size=64)
test_dataloader = DataLoader(test_data, batch_size=64)

In [13]:
class LeNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*4*4, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = nn.functional.relu(self.conv1(x))
        x = nn.functional.max_pool2d(x, 2, 2)
        x = nn.functional.relu(self.conv2(x))
        x = nn.functional.max_pool2d(x, 2, 2)
        x = x.view(-1, 16*4*4)
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
model = LeNet()

In [14]:
# loss function

ce_loss = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        pred = model(X)
        l = loss_fn(pred, y)
        
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
        if batch % 100 == 0:
            loss, current = l.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
            
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return correct



epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, ce_loss, optimizer)
    test(test_dataloader, model, ce_loss)
print("Done!")

Epoch 1
-------------------------------
torch.Size([64, 10]) torch.Size([64])
loss: 2.325374  [    0/60000]
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10]) torch.Size([64])
torch.Size([64, 10