In [3]:
import torch
import torch.nn as nn

In [4]:
linear = nn.Linear(2,3)
print(linear.weight.shape, linear.bias.shape)

torch.Size([3, 2]) torch.Size([3])


In [5]:
linear = nn.Linear(2,3)

print(linear.weight.shape, linear.bias.shape)


torch.Size([3, 2]) torch.Size([3])


In [6]:
x = torch.randn(2,2,2,2)
y = linear(x)
print(y.shape)

y1 = x.matmul(linear.weight.t())
print(y1.shape)

print(y1)
print(linear.bias, linear.bias.shape)
y2 = y1[0,0,0,:] + linear.bias
y1 = torch.add(y1,linear.bias)
nn.functional.avg_pool2d
print(y1[0,0,0,:])
print(y2)



torch.Size([2, 2, 2, 3])
torch.Size([2, 2, 2, 3])
tensor([[[[ 0.0729,  0.0425,  0.2560],
          [-0.9696,  0.1356, -0.2452]],

         [[-0.9448, -0.0039, -0.8519],
          [-0.3079,  0.0283, -0.1444]]],


        [[[-0.5912,  0.1336,  0.0801],
          [-0.2024, -0.1211, -0.7249]],

         [[-0.1338, -0.0049, -0.1403],
          [ 0.4951, -0.0233,  0.3321]]]], grad_fn=<UnsafeViewBackward0>)
Parameter containing:
tensor([-0.4262, -0.4402, -0.1539], requires_grad=True) torch.Size([3])
tensor([-0.3533, -0.3977,  0.1021], grad_fn=<SliceBackward0>)
tensor([-0.3533, -0.3977,  0.1021], grad_fn=<AddBackward0>)


In [7]:
# Tensor broadcasting

a = torch.randn(2, 2, 4)

b = 20
print(a,b)
a = a + b
print(a)

c = torch.randn(2,4)

d = a + c

print(c)
print(a)

e = a * c

c1 = torch.randn(4,2)
print(a.shape, c1.shape)
f = a @ c1

print(e, f)


tensor([[[ 0.7074,  0.3493,  2.1216, -0.6073],
         [-1.3057,  1.7876,  0.0967,  0.8739]],

        [[ 0.0896,  1.5772, -0.3600,  0.6972],
         [-0.9073, -0.0454,  0.0571, -0.6270]]]) 20
tensor([[[20.7074, 20.3493, 22.1216, 19.3927],
         [18.6943, 21.7876, 20.0967, 20.8739]],

        [[20.0896, 21.5772, 19.6400, 20.6972],
         [19.0927, 19.9546, 20.0571, 19.3731]]])
tensor([[ 0.1878,  1.8093,  0.9831,  0.8395],
        [ 1.5020,  0.9427, -0.9425,  1.1161]])
tensor([[[20.7074, 20.3493, 22.1216, 19.3927],
         [18.6943, 21.7876, 20.0967, 20.8739]],

        [[20.0896, 21.5772, 19.6400, 20.6972],
         [19.0927, 19.9546, 20.0571, 19.3731]]])
torch.Size([2, 2, 4]) torch.Size([4, 2])
tensor([[[  3.8888,  36.8177,  21.7480,  16.2811],
         [ 28.0784,  20.5382, -18.9417,  23.2981]],

        [[  3.7727,  39.0393,  19.3083,  17.3763],
         [ 28.6767,  18.8103, -18.9044,  21.6230]]]) tensor([[[50.4971, 12.7446],
         [52.3645, 17.6345]],

        [[51.5845, 

In [8]:
from torchviz import make_dot, make_dot_from_trace

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

make_dot(loss)

ModuleNotFoundError: No module named 'torchviz'