In [1]:
import torch
import torch.nn as nn

In [2]:
input = torch.randn(2,3,4)

print(input.shape)

torch.Size([2, 3, 4])


In [13]:
print(input)
# print(input[0][0][0]**2)
print(input.mean(-1).shape)

tensor([[[-0.8517, -1.0134, -0.8147,  0.7356],
         [ 0.0407, -1.4899, -1.1837, -0.5884],
         [ 0.2723, -0.9320, -0.3147,  1.1367]],

        [[ 1.3157, -1.5664,  0.0989,  0.0206],
         [ 0.0199,  0.0908,  0.7276,  0.0071],
         [ 0.6494,  0.8260,  1.1350, -0.2095]]])
torch.Size([2, 3])


In [18]:
dim = 16
max_len = 5

pe = torch.zeros(max_len, dim) # R shape = [len, dim]

pos = torch.arange(0, max_len, dtype=torch.float) # shape = [len,]

print(pos)

theta = 1 / (dim**0.5) ** (torch.arange(0, dim, 2).float()  / dim)#.to(config.device) / dim) # shape = [dim//2,]

half_pe = torch.outer(pos, theta) # shape = [len, dim//2]
print(half_pe)

pe[:, 0::2] = torch.sin(half_pe)
pe[:, 1::2] = torch.sin(half_pe)


tensor([0., 1., 2., 3., 4.])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 0.8409, 0.7071, 0.5946, 0.5000, 0.4204, 0.3536, 0.2973],
        [2.0000, 1.6818, 1.4142, 1.1892, 1.0000, 0.8409, 0.7071, 0.5946],
        [3.0000, 2.5227, 2.1213, 1.7838, 1.5000, 1.2613, 1.0607, 0.8919],
        [4.0000, 3.3636, 2.8284, 2.3784, 2.0000, 1.6818, 1.4142, 1.1892]])


In [12]:
epsilon = 1e-6

variance = input.pow(2).mean(-1, keepdim=True)
hidden_states = input * torch.rsqrt(variance + epsilon)
print(0.1089**2, input.pow(2))
print(hidden_states)
print(hidden_states.mean(1))
print(hidden_states.mean(-1, keepdim=True))

0.011859209999999999 tensor([[[7.2546e-01, 1.0270e+00, 6.6376e-01, 5.4114e-01],
         [1.6574e-03, 2.2199e+00, 1.4011e+00, 3.4623e-01],
         [7.4154e-02, 8.6856e-01, 9.9030e-02, 1.2920e+00]],

        [[1.7310e+00, 2.4537e+00, 9.7801e-03, 4.2344e-04],
         [3.9466e-04, 8.2361e-03, 5.2938e-01, 5.1037e-05],
         [4.2174e-01, 6.8229e-01, 1.2882e+00, 4.3870e-02]]])
tensor([[[-0.9906, -1.1786, -0.9475,  0.8555],
         [ 0.0409, -1.4958, -1.1883, -0.5907],
         [ 0.3565, -1.2201, -0.4120,  1.4881]],

        [[ 1.2848, -1.5296,  0.0966,  0.0201],
         [ 0.0542,  0.2474,  1.9838,  0.0195],
         [ 0.8322,  1.0584,  1.4544, -0.2684]]])
tensor([[-0.1977, -1.2982, -0.8493,  0.5843],
        [ 0.7237, -0.0746,  1.1782, -0.0763]])
tensor([[[-0.5653],
         [-0.8085],
         [ 0.0531]],

        [[-0.0320],
         [ 0.5762],
         [ 0.7691]]])
